// DO NOT MODIFY -- THIS FILE WAS GENERATED BY `python3 final_generate_icons_h.py`

#ifndef __ICONS_H__
#define __ICONS_H__

#include <cstddef>
#include "icons/icons.inc"

typedef enum icon_name {
  wi_raindrops,
  wifi,
  wifi_1_bar,
  wifi_2_bar,
  wifi_3_bar,
  wifi_x,
  wi_cloud,
  wi_cloudy,
  wi_cloudy_gusts,
  wi_day_cloudy,
  wi_day_cloudy_gusts,
  wi_day_fog,
  wi_day_haze,
  wi_day_rain,
  wi_day_rain_mix,
  wi_day_rain_wind,
  wi_day_showers,
  wi_day_sleet,
  wi_day_snow,
  wi_day_snow_wind,
  wi_day_storm_showers,
  wi_day_sunny,
  wi_day_sunny_overcast,
  wi_day_thunderstorm,
  wi_dust,
  wi_fog,
  wi_na,
  wi_night_alt_cloudy,
  wi_night_alt_cloudy_gusts,
  wi_night_alt_partly_cloudy,
  wi_night_alt_rain,
  wi_night_alt_rain_mix,
  wi_night_alt_rain_wind,
  wi_night_alt_showers,
  wi_night_alt_sleet,
  wi_night_alt_snow,
  wi_night_alt_snow_wind,
  wi_night_alt_storm_showers,
  wi_night_alt_thunderstorm,
  wi_night_clear,
  wi_night_fog,
  wi_rain,
  wi_rain_mix,
  wi_rain_wind,
  wi_sandstorm,
  wi_showers,
  wi_sleet,
  wi_smoke,
  wi_snow,
  wi_snow_wind,
  wi_stars,
  wi_storm_showers,
  wi_strong_wind,
  wi_thunderstorm,
  wi_tornado,
  wi_volcano,
  air_filter,
  battery_0_bar_90deg,
  battery_1_bar_90deg,
  battery_2_bar_90deg,
  battery_3_bar_90deg,
  battery_4_bar_90deg,
  battery_5_bar_90deg,
  battery_6_bar_90deg,
  battery_full_90deg,
  error_icon,
  house_humidity,
  house_thermometer,
  visibility_icon,
  wi_barometer,
  wi_humidity,
  wi_moon_alt_first_quarter,
  wi_moon_alt_full,
  wi_moon_alt_new,
  wi_moon_alt_third_quarter,
  wi_moon_alt_waning_crescent_1,
  wi_moon_alt_waning_crescent_2,
  wi_moon_alt_waning_crescent_3,
  wi_moon_alt_waning_crescent_4,
  wi_moon_alt_waning_crescent_5,
  wi_moon_alt_waning_crescent_6,
  wi_moon_alt_waning_gibbous_1,
  wi_moon_alt_waning_gibbous_2,
  wi_moon_alt_waning_gibbous_3,
  wi_moon_alt_waning_gibbous_4,
  wi_moon_alt_waning_gibbous_5,
  wi_moon_alt_waning_gibbous_6,
  wi_moon_alt_waxing_crescent_1,
  wi_moon_alt_waxing_crescent_2,
  wi_moon_alt_waxing_crescent_3,
  wi_moon_alt_waxing_crescent_4,
  wi_moon_alt_waxing_crescent_5,
  wi_moon_alt_waxing_crescent_6,
  wi_moon_alt_waxing_gibbous_1,
  wi_moon_alt_waxing_gibbous_2,
  wi_moon_alt_waxing_gibbous_3,
  wi_moon_alt_waxing_gibbous_4,
  wi_moon_alt_waxing_gibbous_5,
  wi_moon_alt_waxing_gibbous_6,
  wi_moonrise,
  wi_moonset,
  wi_refresh,
  wi_sunrise,
  wi_sunset,
  wi_thermometer,
  wind_direction_meteorological_0deg,
  wind_direction_meteorological_112_5deg,
  wind_direction_meteorological_135deg,
  wind_direction_meteorological_157_5deg,
  wind_direction_meteorological_180deg,
  wind_direction_meteorological_202_5deg,
  wind_direction_meteorological_225deg,
  wind_direction_meteorological_22_5deg,
  wind_direction_meteorological_247_5deg,
  wind_direction_meteorological_270deg,
  wind_direction_meteorological_292_5deg,
  wind_direction_meteorological_315deg,
  wind_direction_meteorological_337_5deg,
  wind_direction_meteorological_45deg,
  wind_direction_meteorological_67_5deg,
  wind_direction_meteorological_90deg,
  biological_hazard_symbol,
  ionizing_radiation_symbol,
  warning_icon,
  wi_earthquake,
  wi_fire,
  wi_flood,
  wi_gale_warning,
  wi_hurricane,
  wi_hurricane_warning,
  wi_lightning,
  wi_meteor,
  wi_small_craft_advisory,
  wi_smog,
  wi_snowflake_cold,
  wi_storm_warning,
  wi_tsunami,
  battery_alert_0deg,
  wi_cloud_down,
  wi_time_4,
} icon_name_t;

constexpr const unsigned char* getBitmap(icon_name_t icon, size_t size)
{
  switch (icon) {
  case wi_raindrops:
    switch (size) {
    case 16: return wi_raindrops_16x16;
    case 24: return wi_raindrops_24x24;
    default:
      return nullptr;
    }
  case wifi:
    switch (size) {
    case 16: return wifi_16x16;
    default:
      return nullptr;
    }
  case wifi_1_bar:
    switch (size) {
    case 16: return wifi_1_bar_16x16;
    default:
      return nullptr;
    }
  case wifi_2_bar:
    switch (size) {
    case 16: return wifi_2_bar_16x16;
    default:
      return nullptr;
    }
  case wifi_3_bar:
    switch (size) {
    case 16: return wifi_3_bar_16x16;
    default:
      return nullptr;
    }
  case wifi_x:
    switch (size) {
    case 16: return wifi_x_16x16;
    case 96: return wifi_x_96x96;
    default:
      return nullptr;
    }
  case wi_cloud:
    switch (size) {
    case 32: return wi_cloud_32x32;
    case 64: return wi_cloud_64x64;
    case 96: return wi_cloud_96x96;
    case 196: return wi_cloud_196x196;
    default:
      return nullptr;
    }
  case wi_cloudy:
    switch (size) {
    case 32: return wi_cloudy_32x32;
    case 64: return wi_cloudy_64x64;
    case 96: return wi_cloudy_96x96;
    case 196: return wi_cloudy_196x196;
    default:
      return nullptr;
    }
  case wi_cloudy_gusts:
    switch (size) {
    case 32: return wi_cloudy_gusts_32x32;
    case 64: return wi_cloudy_gusts_64x64;
    case 96: return wi_cloudy_gusts_96x96;
    case 196: return wi_cloudy_gusts_196x196;
    default:
      return nullptr;
    }
  case wi_day_cloudy:
    switch (size) {
    case 32: return wi_day_cloudy_32x32;
    case 64: return wi_day_cloudy_64x64;
    case 96: return wi_day_cloudy_96x96;
    case 196: return wi_day_cloudy_196x196;
    default:
      return nullptr;
    }
  case wi_day_cloudy_gusts:
    switch (size) {
    case 32: return wi_day_cloudy_gusts_32x32;
    case 64: return wi_day_cloudy_gusts_64x64;
    case 96: return wi_day_cloudy_gusts_96x96;
    case 196: return wi_day_cloudy_gusts_196x196;
    default:
      return nullptr;
    }
  case wi_day_fog:
    switch (size) {
    case 32: return wi_day_fog_32x32;
    case 64: return wi_day_fog_64x64;
    case 96: return wi_day_fog_96x96;
    case 196: return wi_day_fog_196x196;
    default:
      return nullptr;
    }
  case wi_day_haze:
    switch (size) {
    case 32: return wi_day_haze_32x32;
    case 64: return wi_day_haze_64x64;
    case 96: return wi_day_haze_96x96;
    case 196: return wi_day_haze_196x196;
    default:
      return nullptr;
    }
  case wi_day_rain:
    switch (size) {
    case 32: return wi_day_rain_32x32;
    case 64: return wi_day_rain_64x64;
    case 96: return wi_day_rain_96x96;
    case 196: return wi_day_rain_196x196;
    default:
      return nullptr;
    }
  case wi_day_rain_mix:
    switch (size) {
    case 32: return wi_day_rain_mix_32x32;
    case 64: return wi_day_rain_mix_64x64;
    case 96: return wi_day_rain_mix_96x96;
    case 196: return wi_day_rain_mix_196x196;
    default:
      return nullptr;
    }
  case wi_day_rain_wind:
    switch (size) {
    case 32: return wi_day_rain_wind_32x32;
    case 64: return wi_day_rain_wind_64x64;
    case 96: return wi_day_rain_wind_96x96;
    case 196: return wi_day_rain_wind_196x196;
    default:
      return nullptr;
    }
  case wi_day_showers:
    switch (size) {
    case 32: return wi_day_showers_32x32;
    case 64: return wi_day_showers_64x64;
    case 96: return wi_day_showers_96x96;
    case 196: return wi_day_showers_196x196;
    default:
      return nullptr;
    }
  case wi_day_sleet:
    switch (size) {
    case 32: return wi_day_sleet_32x32;
    case 64: return wi_day_sleet_64x64;
    case 96: return wi_day_sleet_96x96;
    case 196: return wi_day_sleet_196x196;
    default:
      return nullptr;
    }
  case wi_day_snow:
    switch (size) {
    case 32: return wi_day_snow_32x32;
    case 64: return wi_day_snow_64x64;
    case 96: return wi_day_snow_96x96;
    case 196: return wi_day_snow_196x196;
    default:
      return nullptr;
    }
  case wi_day_snow_wind:
    switch (size) {
    case 32: return wi_day_snow_wind_32x32;
    case 64: return wi_day_snow_wind_64x64;
    case 96: return wi_day_snow_wind_96x96;
    case 196: return wi_day_snow_wind_196x196;
    default:
      return nullptr;
    }
  case wi_day_storm_showers:
    switch (size) {
    case 32: return wi_day_storm_showers_32x32;
    case 64: return wi_day_storm_showers_64x64;
    case 96: return wi_day_storm_showers_96x96;
    case 196: return wi_day_storm_showers_196x196;
    default:
      return nullptr;
    }
  case wi_day_sunny:
    switch (size) {
    case 24: return wi_day_sunny_24x24;
    case 32: return wi_day_sunny_32x32;
    case 48: return wi_day_sunny_48x48;
    case 64: return wi_day_sunny_64x64;
    case 96: return wi_day_sunny_96x96;
    case 196: return wi_day_sunny_196x196;
    default:
      return nullptr;
    }
  case wi_day_sunny_overcast:
    switch (size) {
    case 32: return wi_day_sunny_overcast_32x32;
    case 64: return wi_day_sunny_overcast_64x64;
    case 96: return wi_day_sunny_overcast_96x96;
    case 196: return wi_day_sunny_overcast_196x196;
    default:
      return nullptr;
    }
  case wi_day_thunderstorm:
    switch (size) {
    case 32: return wi_day_thunderstorm_32x32;
    case 64: return wi_day_thunderstorm_64x64;
    case 96: return wi_day_thunderstorm_96x96;
    case 196: return wi_day_thunderstorm_196x196;
    default:
      return nullptr;
    }
  case wi_dust:
    switch (size) {
    case 32: return wi_dust_32x32;
    case 48: return wi_dust_48x48;
    case 64: return wi_dust_64x64;
    case 96: return wi_dust_96x96;
    case 196: return wi_dust_196x196;
    default:
      return nullptr;
    }
  case wi_fog:
    switch (size) {
    case 32: return wi_fog_32x32;
    case 48: return wi_fog_48x48;
    case 64: return wi_fog_64x64;
    case 96: return wi_fog_96x96;
    case 196: return wi_fog_196x196;
    default:
      return nullptr;
    }
  case wi_na:
    switch (size) {
    case 32: return wi_na_32x32;
    case 48: return wi_na_48x48;
    case 64: return wi_na_64x64;
    case 96: return wi_na_96x96;
    case 196: return wi_na_196x196;
    default:
      return nullptr;
    }
  case wi_night_alt_cloudy:
    switch (size) {
    case 32: return wi_night_alt_cloudy_32x32;
    case 64: return wi_night_alt_cloudy_64x64;
    case 96: return wi_night_alt_cloudy_96x96;
    case 196: return wi_night_alt_cloudy_196x196;
    default:
      return nullptr;
    }
  case wi_night_alt_cloudy_gusts:
    switch (size) {
    case 32: return wi_night_alt_cloudy_gusts_32x32;
    case 64: return wi_night_alt_cloudy_gusts_64x64;
    case 96: return wi_night_alt_cloudy_gusts_96x96;
    case 196: return wi_night_alt_cloudy_gusts_196x196;
    default:
      return nullptr;
    }
  case wi_night_alt_partly_cloudy:
    switch (size) {
    case 32: return wi_night_alt_partly_cloudy_32x32;
    case 64: return wi_night_alt_partly_cloudy_64x64;
    case 96: return wi_night_alt_partly_cloudy_96x96;
    case 196: return wi_night_alt_partly_cloudy_196x196;
    default:
      return nullptr;
    }
  case wi_night_alt_rain:
    switch (size) {
    case 32: return wi_night_alt_rain_32x32;
    case 64: return wi_night_alt_rain_64x64;
    case 96: return wi_night_alt_rain_96x96;
    case 196: return wi_night_alt_rain_196x196;
    default:
      return nullptr;
    }
  case wi_night_alt_rain_mix:
    switch (size) {
    case 32: return wi_night_alt_rain_mix_32x32;
    case 64: return wi_night_alt_rain_mix_64x64;
    case 96: return wi_night_alt_rain_mix_96x96;
    case 196: return wi_night_alt_rain_mix_196x196;
    default:
      return nullptr;
    }
  case wi_night_alt_rain_wind:
    switch (size) {
    case 32: return wi_night_alt_rain_wind_32x32;
    case 64: return wi_night_alt_rain_wind_64x64;
    case 96: return wi_night_alt_rain_wind_96x96;
    case 196: return wi_night_alt_rain_wind_196x196;
    default:
      return nullptr;
    }
  case wi_night_alt_showers:
    switch (size) {
    case 32: return wi_night_alt_showers_32x32;
    case 64: return wi_night_alt_showers_64x64;
    case 96: return wi_night_alt_showers_96x96;
    case 196: return wi_night_alt_showers_196x196;
    default:
      return nullptr;
    }
  case wi_night_alt_sleet:
    switch (size) {
    case 32: return wi_night_alt_sleet_32x32;
    case 64: return wi_night_alt_sleet_64x64;
    case 96: return wi_night_alt_sleet_96x96;
    case 196: return wi_night_alt_sleet_196x196;
    default:
      return nullptr;
    }
  case wi_night_alt_snow:
    switch (size) {
    case 32: return wi_night_alt_snow_32x32;
    case 64: return wi_night_alt_snow_64x64;
    case 96: return wi_night_alt_snow_96x96;
    case 196: return wi_night_alt_snow_196x196;
    default:
      return nullptr;
    }
  case wi_night_alt_snow_wind:
    switch (size) {
    case 32: return wi_night_alt_snow_wind_32x32;
    case 64: return wi_night_alt_snow_wind_64x64;
    case 96: return wi_night_alt_snow_wind_96x96;
    case 196: return wi_night_alt_snow_wind_196x196;
    default:
      return nullptr;
    }
  case wi_night_alt_storm_showers:
    switch (size) {
    case 32: return wi_night_alt_storm_showers_32x32;
    case 64: return wi_night_alt_storm_showers_64x64;
    case 96: return wi_night_alt_storm_showers_96x96;
    case 196: return wi_night_alt_storm_showers_196x196;
    default:
      return nullptr;
    }
  case wi_night_alt_thunderstorm:
    switch (size) {
    case 32: return wi_night_alt_thunderstorm_32x32;
    case 64: return wi_night_alt_thunderstorm_64x64;
    case 96: return wi_night_alt_thunderstorm_96x96;
    case 196: return wi_night_alt_thunderstorm_196x196;
    default:
      return nullptr;
    }
  case wi_night_clear:
    switch (size) {
    case 32: return wi_night_clear_32x32;
    case 64: return wi_night_clear_64x64;
    case 96: return wi_night_clear_96x96;
    case 196: return wi_night_clear_196x196;
    default:
      return nullptr;
    }
  case wi_night_fog:
    switch (size) {
    case 32: return wi_night_fog_32x32;
    case 64: return wi_night_fog_64x64;
    case 96: return wi_night_fog_96x96;
    case 196: return wi_night_fog_196x196;
    default:
      return nullptr;
    }
  case wi_rain:
    switch (size) {
    case 32: return wi_rain_32x32;
    case 64: return wi_rain_64x64;
    case 96: return wi_rain_96x96;
    case 196: return wi_rain_196x196;
    default:
      return nullptr;
    }
  case wi_rain_mix:
    switch (size) {
    case 32: return wi_rain_mix_32x32;
    case 64: return wi_rain_mix_64x64;
    case 96: return wi_rain_mix_96x96;
    case 196: return wi_rain_mix_196x196;
    default:
      return nullptr;
    }
  case wi_rain_wind:
    switch (size) {
    case 32: return wi_rain_wind_32x32;
    case 64: return wi_rain_wind_64x64;
    case 96: return wi_rain_wind_96x96;
    case 196: return wi_rain_wind_196x196;
    default:
      return nullptr;
    }
  case wi_sandstorm:
    switch (size) {
    case 32: return wi_sandstorm_32x32;
    case 48: return wi_sandstorm_48x48;
    case 64: return wi_sandstorm_64x64;
    case 96: return wi_sandstorm_96x96;
    case 196: return wi_sandstorm_196x196;
    default:
      return nullptr;
    }
  case wi_showers:
    switch (size) {
    case 32: return wi_showers_32x32;
    case 64: return wi_showers_64x64;
    case 96: return wi_showers_96x96;
    case 196: return wi_showers_196x196;
    default:
      return nullptr;
    }
  case wi_sleet:
    switch (size) {
    case 32: return wi_sleet_32x32;
    case 64: return wi_sleet_64x64;
    case 96: return wi_sleet_96x96;
    case 196: return wi_sleet_196x196;
    default:
      return nullptr;
    }
  case wi_smoke:
    switch (size) {
    case 32: return wi_smoke_32x32;
    case 48: return wi_smoke_48x48;
    case 64: return wi_smoke_64x64;
    case 96: return wi_smoke_96x96;
    case 196: return wi_smoke_196x196;
    default:
      return nullptr;
    }
  case wi_snow:
    switch (size) {
    case 32: return wi_snow_32x32;
    case 64: return wi_snow_64x64;
    case 96: return wi_snow_96x96;
    case 196: return wi_snow_196x196;
    default:
      return nullptr;
    }
  case wi_snow_wind:
    switch (size) {
    case 32: return wi_snow_wind_32x32;
    case 64: return wi_snow_wind_64x64;
    case 96: return wi_snow_wind_96x96;
    case 196: return wi_snow_wind_196x196;
    default:
      return nullptr;
    }
  case wi_stars:
    switch (size) {
    case 32: return wi_stars_32x32;
    case 64: return wi_stars_64x64;
    case 96: return wi_stars_96x96;
    case 196: return wi_stars_196x196;
    default:
      return nullptr;
    }
  case wi_storm_showers:
    switch (size) {
    case 32: return wi_storm_showers_32x32;
    case 64: return wi_storm_showers_64x64;
    case 96: return wi_storm_showers_96x96;
    case 196: return wi_storm_showers_196x196;
    default:
      return nullptr;
    }
  case wi_strong_wind:
    switch (size) {
    case 24: return wi_strong_wind_24x24;
    case 32: return wi_strong_wind_32x32;
    case 48: return wi_strong_wind_48x48;
    case 64: return wi_strong_wind_64x64;
    case 96: return wi_strong_wind_96x96;
    case 196: return wi_strong_wind_196x196;
    default:
      return nullptr;
    }
  case wi_thunderstorm:
    switch (size) {
    case 32: return wi_thunderstorm_32x32;
    case 64: return wi_thunderstorm_64x64;
    case 96: return wi_thunderstorm_96x96;
    case 196: return wi_thunderstorm_196x196;
    default:
      return nullptr;
    }
  case wi_tornado:
    switch (size) {
    case 32: return wi_tornado_32x32;
    case 48: return wi_tornado_48x48;
    case 64: return wi_tornado_64x64;
    case 96: return wi_tornado_96x96;
    case 196: return wi_tornado_196x196;
    default:
      return nullptr;
    }
  case wi_volcano:
    switch (size) {
    case 32: return wi_volcano_32x32;
    case 48: return wi_volcano_48x48;
    case 64: return wi_volcano_64x64;
    case 96: return wi_volcano_96x96;
    case 196: return wi_volcano_196x196;
    default:
      return nullptr;
    }
  case air_filter:
    switch (size) {
    case 24: return air_filter_24x24;
    case 48: return air_filter_48x48;
    default:
      return nullptr;
    }
  case battery_0_bar_90deg:
    switch (size) {
    case 24: return battery_0_bar_90deg_24x24;
    default:
      return nullptr;
    }
  case battery_1_bar_90deg:
    switch (size) {
    case 24: return battery_1_bar_90deg_24x24;
    default:
      return nullptr;
    }
  case battery_2_bar_90deg:
    switch (size) {
    case 24: return battery_2_bar_90deg_24x24;
    default:
      return nullptr;
    }
  case battery_3_bar_90deg:
    switch (size) {
    case 24: return battery_3_bar_90deg_24x24;
    default:
      return nullptr;
    }
  case battery_4_bar_90deg:
    switch (size) {
    case 24: return battery_4_bar_90deg_24x24;
    default:
      return nullptr;
    }
  case battery_5_bar_90deg:
    switch (size) {
    case 24: return battery_5_bar_90deg_24x24;
    default:
      return nullptr;
    }
  case battery_6_bar_90deg:
    switch (size) {
    case 24: return battery_6_bar_90deg_24x24;
    default:
      return nullptr;
    }
  case battery_full_90deg:
    switch (size) {
    case 24: return battery_full_90deg_24x24;
    default:
      return nullptr;
    }
  case error_icon:
    switch (size) {
    case 24: return error_icon_24x24;
    default:
      return nullptr;
    }
  case house_humidity:
    switch (size) {
    case 24: return house_humidity_24x24;
    case 48: return house_humidity_48x48;
    default:
      return nullptr;
    }
  case house_thermometer:
    switch (size) {
    case 24: return house_thermometer_24x24;
    case 48: return house_thermometer_48x48;
    default:
      return nullptr;
    }
  case visibility_icon:
    switch (size) {
    case 24: return visibility_icon_24x24;
    case 48: return visibility_icon_48x48;
    default:
      return nullptr;
    }
  case wi_barometer:
    switch (size) {
    case 24: return wi_barometer_24x24;
    case 48: return wi_barometer_48x48;
    default:
      return nullptr;
    }
  case wi_humidity:
    switch (size) {
    case 24: return wi_humidity_24x24;
    case 48: return wi_humidity_48x48;
    default:
      return nullptr;
    }
  case wi_moon_alt_first_quarter:
    switch (size) {
    case 24: return wi_moon_alt_first_quarter_24x24;
    case 48: return wi_moon_alt_first_quarter_48x48;
    default:
      return nullptr;
    }
  case wi_moon_alt_full:
    switch (size) {
    case 24: return wi_moon_alt_full_24x24;
    case 48: return wi_moon_alt_full_48x48;
    default:
      return nullptr;
    }
  case wi_moon_alt_new:
    switch (size) {
    case 24: return wi_moon_alt_new_24x24;
    case 48: return wi_moon_alt_new_48x48;
    default:
      return nullptr;
    }
  case wi_moon_alt_third_quarter:
    switch (size) {
    case 24: return wi_moon_alt_third_quarter_24x24;
    case 48: return wi_moon_alt_third_quarter_48x48;
    default:
      return nullptr;
    }
  case wi_moon_alt_waning_crescent_1:
    switch (size) {
    case 24: return wi_moon_alt_waning_crescent_1_24x24;
    case 48: return wi_moon_alt_waning_crescent_1_48x48;
    default:
      return nullptr;
    }
  case wi_moon_alt_waning_crescent_2:
    switch (size) {
    case 24: return wi_moon_alt_waning_crescent_2_24x24;
    case 48: return wi_moon_alt_waning_crescent_2_48x48;
    default:
      return nullptr;
    }
  case wi_moon_alt_waning_crescent_3:
    switch (size) {
    case 24: return wi_moon_alt_waning_crescent_3_24x24;
    case 48: return wi_moon_alt_waning_crescent_3_48x48;
    default:
      return nullptr;
    }
  case wi_moon_alt_waning_crescent_4:
    switch (size) {
    case 24: return wi_moon_alt_waning_crescent_4_24x24;
    case 48: return wi_moon_alt_waning_crescent_4_48x48;
    default:
      return nullptr;
    }
  case wi_moon_alt_waning_crescent_5:
    switch (size) {
    case 24: return wi_moon_alt_waning_crescent_5_24x24;
    case 48: return wi_moon_alt_waning_crescent_5_48x48;
    default:
      return nullptr;
    }
  case wi_moon_alt_waning_crescent_6:
    switch (size) {
    case 24: return wi_moon_alt_waning_crescent_6_24x24;
    case 48: return wi_moon_alt_waning_crescent_6_48x48;
    default:
      return nullptr;
    }
  case wi_moon_alt_waning_gibbous_1:
    switch (size) {
    case 24: return wi_moon_alt_waning_gibbous_1_24x24;
    case 48: return wi_moon_alt_waning_gibbous_1_48x48;
    default:
      return nullptr;
    }
  case wi_moon_alt_waning_gibbous_2:
    switch (size) {
    case 24: return wi_moon_alt_waning_gibbous_2_24x24;
    case 48: return wi_moon_alt_waning_gibbous_2_48x48;
    default:
      return nullptr;
    }
  case wi_moon_alt_waning_gibbous_3:
    switch (size) {
    case 24: return wi_moon_alt_waning_gibbous_3_24x24;
    case 48: return wi_moon_alt_waning_gibbous_3_48x48;
    default:
      return nullptr;
    }
  case wi_moon_alt_waning_gibbous_4:
    switch (size) {
    case 24: return wi_moon_alt_waning_gibbous_4_24x24;
    case 48: return wi_moon_alt_waning_gibbous_4_48x48;
    default:
      return nullptr;
    }
  case wi_moon_alt_waning_gibbous_5:
    switch (size) {
    case 24: return wi_moon_alt_waning_gibbous_5_24x24;
    case 48: return wi_moon_alt_waning_gibbous_5_48x48;
    default:
      return nullptr;
    }
  case wi_moon_alt_waning_gibbous_6:
    switch (size) {
    case 24: return wi_moon_alt_waning_gibbous_6_24x24;
    case 48: return wi_moon_alt_waning_gibbous_6_48x48;
    default:
      return nullptr;
    }
  case wi_moon_alt_waxing_crescent_1:
    switch (size) {
    case 24: return wi_moon_alt_waxing_crescent_1_24x24;
    case 48: return wi_moon_alt_waxing_crescent_1_48x48;
    default:
      return nullptr;
    }
  case wi_moon_alt_waxing_crescent_2:
    switch (size) {
    case 24: return wi_moon_alt_waxing_crescent_2_24x24;
    case 48: return wi_moon_alt_waxing_crescent_2_48x48;
    default:
      return nullptr;
    }
  case wi_moon_alt_waxing_crescent_3:
    switch (size) {
    case 24: return wi_moon_alt_waxing_crescent_3_24x24;
    case 48: return wi_moon_alt_waxing_crescent_3_48x48;
    default:
      return nullptr;
    }
  case wi_moon_alt_waxing_crescent_4:
    switch (size) {
    case 24: return wi_moon_alt_waxing_crescent_4_24x24;
    case 48: return wi_moon_alt_waxing_crescent_4_48x48;
    default:
      return nullptr;
    }
  case wi_moon_alt_waxing_crescent_5:
    switch (size) {
    case 24: return wi_moon_alt_waxing_crescent_5_24x24;
    case 48: return wi_moon_alt_waxing_crescent_5_48x48;
    default:
      return nullptr;
    }
  case wi_moon_alt_waxing_crescent_6:
    switch (size) {
    case 24: return wi_moon_alt_waxing_crescent_6_24x24;
    case 48: return wi_moon_alt_waxing_crescent_6_48x48;
    default:
      return nullptr;
    }
  case wi_moon_alt_waxing_gibbous_1:
    switch (size) {
    case 24: return wi_moon_alt_waxing_gibbous_1_24x24;
    case 48: return wi_moon_alt_waxing_gibbous_1_48x48;
    default:
      return nullptr;
    }
  case wi_moon_alt_waxing_gibbous_2:
    switch (size) {
    case 24: return wi_moon_alt_waxing_gibbous_2_24x24;
    case 48: return wi_moon_alt_waxing_gibbous_2_48x48;
    default:
      return nullptr;
    }
  case wi_moon_alt_waxing_gibbous_3:
    switch (size) {
    case 24: return wi_moon_alt_waxing_gibbous_3_24x24;
    case 48: return wi_moon_alt_waxing_gibbous_3_48x48;
    default:
      return nullptr;
    }
  case wi_moon_alt_waxing_gibbous_4:
    switch (size) {
    case 24: return wi_moon_alt_waxing_gibbous_4_24x24;
    case 48: return wi_moon_alt_waxing_gibbous_4_48x48;
    default:
      return nullptr;
    }
  case wi_moon_alt_waxing_gibbous_5:
    switch (size) {
    case 24: return wi_moon_alt_waxing_gibbous_5_24x24;
    case 48: return wi_moon_alt_waxing_gibbous_5_48x48;
    default:
      return nullptr;
    }
  case wi_moon_alt_waxing_gibbous_6:
    switch (size) {
    case 24: return wi_moon_alt_waxing_gibbous_6_24x24;
    case 48: return wi_moon_alt_waxing_gibbous_6_48x48;
    default:
      return nullptr;
    }
  case wi_moonrise:
    switch (size) {
    case 24: return wi_moonrise_24x24;
    case 48: return wi_moonrise_48x48;
    default:
      return nullptr;
    }
  case wi_moonset:
    switch (size) {
    case 24: return wi_moonset_24x24;
    case 48: return wi_moonset_48x48;
    default:
      return nullptr;
    }
  case wi_refresh:
    switch (size) {
    case 24: return wi_refresh_24x24;
    case 32: return wi_refresh_32x32;
    default:
      return nullptr;
    }
  case wi_sunrise:
    switch (size) {
    case 24: return wi_sunrise_24x24;
    case 48: return wi_sunrise_48x48;
    default:
      return nullptr;
    }
  case wi_sunset:
    switch (size) {
    case 24: return wi_sunset_24x24;
    case 48: return wi_sunset_48x48;
    default:
      return nullptr;
    }
  case wi_thermometer:
    switch (size) {
    case 24: return wi_thermometer_24x24;
    case 32: return wi_thermometer_32x32;
    case 48: return wi_thermometer_48x48;
    default:
      return nullptr;
    }
  case wind_direction_meteorological_0deg:
    switch (size) {
    case 24: return wind_direction_meteorological_0deg_24x24;
    default:
      return nullptr;
    }
  case wind_direction_meteorological_112_5deg:
    switch (size) {
    case 24: return wind_direction_meteorological_112_5deg_24x24;
    default:
      return nullptr;
    }
  case wind_direction_meteorological_135deg:
    switch (size) {
    case 24: return wind_direction_meteorological_135deg_24x24;
    default:
      return nullptr;
    }
  case wind_direction_meteorological_157_5deg:
    switch (size) {
    case 24: return wind_direction_meteorological_157_5deg_24x24;
    default:
      return nullptr;
    }
  case wind_direction_meteorological_180deg:
    switch (size) {
    case 24: return wind_direction_meteorological_180deg_24x24;
    default:
      return nullptr;
    }
  case wind_direction_meteorological_202_5deg:
    switch (size) {
    case 24: return wind_direction_meteorological_202_5deg_24x24;
    default:
      return nullptr;
    }
  case wind_direction_meteorological_225deg:
    switch (size) {
    case 24: return wind_direction_meteorological_225deg_24x24;
    default:
      return nullptr;
    }
  case wind_direction_meteorological_22_5deg:
    switch (size) {
    case 24: return wind_direction_meteorological_22_5deg_24x24;
    default:
      return nullptr;
    }
  case wind_direction_meteorological_247_5deg:
    switch (size) {
    case 24: return wind_direction_meteorological_247_5deg_24x24;
    default:
      return nullptr;
    }
  case wind_direction_meteorological_270deg:
    switch (size) {
    case 24: return wind_direction_meteorological_270deg_24x24;
    default:
      return nullptr;
    }
  case wind_direction_meteorological_292_5deg:
    switch (size) {
    case 24: return wind_direction_meteorological_292_5deg_24x24;
    default:
      return nullptr;
    }
  case wind_direction_meteorological_315deg:
    switch (size) {
    case 24: return wind_direction_meteorological_315deg_24x24;
    default:
      return nullptr;
    }
  case wind_direction_meteorological_337_5deg:
    switch (size) {
    case 24: return wind_direction_meteorological_337_5deg_24x24;
    default:
      return nullptr;
    }
  case wind_direction_meteorological_45deg:
    switch (size) {
    case 24: return wind_direction_meteorological_45deg_24x24;
    default:
      return nullptr;
    }
  case wind_direction_meteorological_67_5deg:
    switch (size) {
    case 24: return wind_direction_meteorological_67_5deg_24x24;
    default:
      return nullptr;
    }
  case wind_direction_meteorological_90deg:
    switch (size) {
    case 24: return wind_direction_meteorological_90deg_24x24;
    default:
      return nullptr;
    }
  case biological_hazard_symbol:
    switch (size) {
    case 32: return biological_hazard_symbol_32x32;
    case 48: return biological_hazard_symbol_48x48;
    default:
      return nullptr;
    }
  case ionizing_radiation_symbol:
    switch (size) {
    case 32: return ionizing_radiation_symbol_32x32;
    case 48: return ionizing_radiation_symbol_48x48;
    default:
      return nullptr;
    }
  case warning_icon:
    switch (size) {
    case 32: return warning_icon_32x32;
    case 48: return warning_icon_48x48;
    default:
      return nullptr;
    }
  case wi_earthquake:
    switch (size) {
    case 32: return wi_earthquake_32x32;
    case 48: return wi_earthquake_48x48;
    default:
      return nullptr;
    }
  case wi_fire:
    switch (size) {
    case 32: return wi_fire_32x32;
    case 48: return wi_fire_48x48;
    default:
      return nullptr;
    }
  case wi_flood:
    switch (size) {
    case 32: return wi_flood_32x32;
    case 48: return wi_flood_48x48;
    default:
      return nullptr;
    }
  case wi_gale_warning:
    switch (size) {
    case 32: return wi_gale_warning_32x32;
    case 48: return wi_gale_warning_48x48;
    default:
      return nullptr;
    }
  case wi_hurricane:
    switch (size) {
    case 32: return wi_hurricane_32x32;
    case 48: return wi_hurricane_48x48;
    default:
      return nullptr;
    }
  case wi_hurricane_warning:
    switch (size) {
    case 32: return wi_hurricane_warning_32x32;
    case 48: return wi_hurricane_warning_48x48;
    default:
      return nullptr;
    }
  case wi_lightning:
    switch (size) {
    case 32: return wi_lightning_32x32;
    case 48: return wi_lightning_48x48;
    default:
      return nullptr;
    }
  case wi_meteor:
    switch (size) {
    case 32: return wi_meteor_32x32;
    case 48: return wi_meteor_48x48;
    default:
      return nullptr;
    }
  case wi_small_craft_advisory:
    switch (size) {
    case 32: return wi_small_craft_advisory_32x32;
    case 48: return wi_small_craft_advisory_48x48;
    default:
      return nullptr;
    }
  case wi_smog:
    switch (size) {
    case 32: return wi_smog_32x32;
    case 48: return wi_smog_48x48;
    default:
      return nullptr;
    }
  case wi_snowflake_cold:
    switch (size) {
    case 32: return wi_snowflake_cold_32x32;
    case 48: return wi_snowflake_cold_48x48;
    default:
      return nullptr;
    }
  case wi_storm_warning:
    switch (size) {
    case 32: return wi_storm_warning_32x32;
    case 48: return wi_storm_warning_48x48;
    default:
      return nullptr;
    }
  case wi_tsunami:
    switch (size) {
    case 32: return wi_tsunami_32x32;
    case 48: return wi_tsunami_48x48;
    default:
      return nullptr;
    }
  case battery_alert_0deg:
    switch (size) {
    case 96: return battery_alert_0deg_96x96;
    default:
      return nullptr;
    }
  case wi_cloud_down:
    switch (size) {
    case 96: return wi_cloud_down_96x96;
    default:
      return nullptr;
    }
  case wi_time_4:
    switch (size) {
    case 96: return wi_time_4_96x96;
    default:
      return nullptr;
    }
  default:
    return nullptr;
  }
}

#endif